CREATE SCHEMA "app";
--> statement-breakpoint
CREATE TYPE "app"."gender_type" AS ENUM('male', 'female', 'others');--> statement-breakpoint
CREATE TABLE "app"."club_addresses" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.club_address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"street_name" varchar(60) NOT NULL,
	"street_number" varchar(20) NOT NULL,
	"zip" varchar(14) NOT NULL,
	"city" varchar(100) NOT NULL,
	"region" varchar(100),
	"country_id" bigint,
	"name" varchar(60) NOT NULL,
	"short" varchar(20) NOT NULL,
	"directions" varchar(255),
	"primary" boolean,
	"active" boolean,
	"club_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "club_address_primary_active_check" CHECK ((active IS DISTINCT FROM false) OR ("primary" IS DISTINCT FROM true))
);
--> statement-breakpoint
CREATE TABLE "app"."club_age_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.club_age_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"club_id" bigint NOT NULL,
	"name" varchar(30) NOT NULL,
	"sn" varchar(8) NOT NULL,
	"age_min" smallint,
	"age_max" smallint,
	"active" boolean NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "club_age_group_age_max_check" CHECK ((age_max > 0) AND (age_max <= 120)),
	CONSTRAINT "club_age_group_age_min_check" CHECK ((age_min > 0) AND (age_min <= 120))
);
--> statement-breakpoint
CREATE TABLE "app"."club_emails" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.club_email_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"club_id" bigint NOT NULL,
	"email" varchar(255),
	"description" varchar(30),
	"sorting_order" smallint,
	"primary" boolean,
	"active" boolean,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."club_phone_numbers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.club_telephone_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"club_id" bigint NOT NULL,
	"country_code" smallint,
	"phone_number" varchar(14),
	"description" varchar(20),
	"primary" boolean,
	"active" boolean,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "club_telephone_country_code_check" CHECK ((country_code > 0) AND (country_code <= 999))
);
--> statement-breakpoint
CREATE TABLE "app"."club_questionnaire_details" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.club_questionnaire_detail_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"questionnaire_id" bigint NOT NULL,
	"language_id" bigint NOT NULL,
	"sort" smallint NOT NULL,
	"question" varchar(254) NOT NULL,
	"active" boolean NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."club_questionnaires" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.club_questionnaire_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"club_id" bigint NOT NULL,
	"questionnaire_name" varchar(60) NOT NULL,
	"multi_linguistic" boolean NOT NULL,
	"language_id" bigint,
	"save" smallint DEFAULT 90 NOT NULL,
	"active" boolean NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "club_questionnaire_language_check" CHECK ((multi_linguistic = true) OR (language_id IS NOT NULL)),
	CONSTRAINT "club_questionnaire_save_check" CHECK ((save > 0) AND (save <= 999))
);
--> statement-breakpoint
CREATE TABLE "app"."club_waitlists" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.club_waitlist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"club_id" bigint NOT NULL,
	"waitlist" varchar(30) NOT NULL,
	"gender_id" bigint,
	"questionary_id" bigint,
	"active" boolean,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."clubs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.clubs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"sn" varchar(10) NOT NULL,
	"date" date,
	"avatar1_id" bigint,
	"avatar2_id" bigint,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."genders" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.gender_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"gender" "app"."gender_type" NOT NULL,
	CONSTRAINT "genders_gender_key" UNIQUE("gender")
);
--> statement-breakpoint
CREATE TABLE "app"."location_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.location_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"club_id" bigint NOT NULL,
	"name" varchar(80) NOT NULL,
	"sn" varchar(10) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."location_relations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.location_relation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"location_group_id" bigint NOT NULL,
	"location_id" bigint NOT NULL,
	"active" boolean NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."locations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.locations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"club_id" bigint NOT NULL,
	"name" varchar(60) NOT NULL,
	"directions" varchar(255),
	"sn" varchar(8) NOT NULL,
	"club_address_id" bigint,
	"mbr_book" boolean,
	"t_book" boolean NOT NULL,
	"no_mbr" smallint,
	"pub" boolean NOT NULL,
	"fc" boolean NOT NULL,
	"active" boolean NOT NULL,
	"parent_location_id" bigint,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "locations_mbr_book_no_mbr_check" CHECK ((mbr_book IS NOT TRUE) OR (no_mbr IS NOT NULL)),
	CONSTRAINT "locations_no_mbr_check" CHECK ((no_mbr > 0) AND (no_mbr <= 30))
);
--> statement-breakpoint
CREATE TABLE "app"."user_addresses" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"street_name" varchar(60) NOT NULL,
	"street_number" varchar(20) NOT NULL,
	"zip" varchar(14) NOT NULL,
	"city" varchar(100) NOT NULL,
	"region" varchar(100),
	"country_id" uuid NOT NULL,
	"primary" boolean DEFAULT false NOT NULL,
	"active" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."user_aliases" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.alias_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"alias" varchar(11) NOT NULL,
	"primary" boolean DEFAULT false NOT NULL,
	"active" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "alias_alias_key" UNIQUE("alias")
);
--> statement-breakpoint
CREATE TABLE "app"."user_emails" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.mail_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"email" varchar(254),
	"primary" boolean DEFAULT false,
	"active" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "mail_email_key" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "app"."user_phone_numbers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.phone_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"country_code" integer,
	"phone_number" varchar(14),
	"primary" boolean DEFAULT false,
	"active" boolean DEFAULT false,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "user_phone_numbers_country_code_phone_number_unique" UNIQUE("phone_number","country_code"),
	CONSTRAINT "phone_check" CHECK ((country_code IS NULL) OR (phone_number IS NULL) OR ((length((country_code)::text) + length((phone_number)::text)) <= 14)),
	CONSTRAINT "phone_country_code_check" CHECK ((country_code > 0) AND (country_code <= 9999))
);
--> statement-breakpoint
CREATE TABLE "app"."user_security_numbers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.user_security_numbers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"social_security_number" varchar(11),
	"active" boolean NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."users" (
	"uuid" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"firstname" text NOT NULL,
	"surname" text NOT NULL,
	"nickname" text NOT NULL,
	"dob" date NOT NULL,
	"gender" bigint NOT NULL,
	"preferred_lang" varchar(15) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."club_addresses" ADD CONSTRAINT "club_address_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_age_groups" ADD CONSTRAINT "club_age_group_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_emails" ADD CONSTRAINT "club_email_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_phone_numbers" ADD CONSTRAINT "club_telephone_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_questionnaire_details" ADD CONSTRAINT "club_questionnaire_detail_questionnaire_id_fkey" FOREIGN KEY ("questionnaire_id") REFERENCES "app"."club_questionnaires"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_questionnaires" ADD CONSTRAINT "club_questionnaire_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_waitlists" ADD CONSTRAINT "club_waitlist_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_waitlists" ADD CONSTRAINT "club_waitlist_gender_id_fkey" FOREIGN KEY ("gender_id") REFERENCES "app"."genders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_waitlists" ADD CONSTRAINT "club_waitlist_questionary_fkey" FOREIGN KEY ("questionary_id") REFERENCES "app"."club_questionnaires"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."location_groups" ADD CONSTRAINT "location_group_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."location_relations" ADD CONSTRAINT "location_relation_location_group_id_fkey" FOREIGN KEY ("location_group_id") REFERENCES "app"."location_groups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."location_relations" ADD CONSTRAINT "location_relation_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "app"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."locations" ADD CONSTRAINT "locations_club_address_id_fkey" FOREIGN KEY ("club_address_id") REFERENCES "app"."club_addresses"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."locations" ADD CONSTRAINT "locations_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."locations" ADD CONSTRAINT "locations_parent_location_id_fkey" FOREIGN KEY ("parent_location_id") REFERENCES "app"."locations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."user_addresses" ADD CONSTRAINT "address_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."users"("uuid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."user_aliases" ADD CONSTRAINT "alias_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."users"("uuid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."user_emails" ADD CONSTRAINT "mail_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."users"("uuid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."user_phone_numbers" ADD CONSTRAINT "phone_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."users"("uuid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."user_security_numbers" ADD CONSTRAINT "user_security_numbers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."users"("uuid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."users" ADD CONSTRAINT "users_gender_fkey" FOREIGN KEY ("gender") REFERENCES "app"."genders"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "users_gender_idx" ON "app"."users" USING btree ("gender" int8_ops);