CREATE TABLE "app"."user_avatars" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.user_avatar_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"avatar1" text,
	"avatar2" text,
	"avatar3" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "user_avatars_user_id_key" UNIQUE("user_id")
);
--> statement-breakpoint
ALTER TABLE "app"."user_avatars" ADD CONSTRAINT "user_avatars_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."users"("uuid") ON DELETE cascade ON UPDATE no action;