ALTER TABLE "app"."clubs" ADD COLUMN "active" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."clubs" ADD COLUMN "country_code" varchar(2);--> statement-breakpoint
UPDATE "app"."clubs" SET "country_code" = 'DK' WHERE "country_code" IS NULL;--> statement-breakpoint
ALTER TABLE "app"."clubs" ALTER COLUMN "country_code" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."clubs" DROP COLUMN IF EXISTS "avatar1_id";--> statement-breakpoint
ALTER TABLE "app"."clubs" DROP COLUMN IF EXISTS "avatar2_id";--> statement-breakpoint
ALTER TABLE "app"."clubs" ADD CONSTRAINT "clubs_sn_key" UNIQUE("sn");--> statement-breakpoint
UPDATE "app"."club_addresses" SET "primary" = false WHERE "primary" IS NULL;--> statement-breakpoint
ALTER TABLE "app"."club_addresses" ALTER COLUMN "primary" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "app"."club_addresses" ALTER COLUMN "primary" SET NOT NULL;--> statement-breakpoint
UPDATE "app"."club_addresses" SET "active" = true WHERE "active" IS NULL;--> statement-breakpoint
ALTER TABLE "app"."club_addresses" ALTER COLUMN "active" SET DEFAULT true;--> statement-breakpoint
CREATE TABLE "app"."activities" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.activities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(80) NOT NULL,
	"sn" varchar(10) NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "activities_sn_key" UNIQUE("sn")
);
--> statement-breakpoint
CREATE TABLE "app"."languages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.languages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"code" varchar(15) NOT NULL,
	"name" varchar(80) NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "languages_code_key" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "app"."club_admins" (
	"club_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "club_admins_pkey" PRIMARY KEY("club_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "app"."club_activities" (
	"club_id" bigint NOT NULL,
	"activity_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "club_activities_pkey" PRIMARY KEY("club_id","activity_id")
);
--> statement-breakpoint
CREATE TABLE "app"."club_languages" (
	"club_id" bigint NOT NULL,
	"language_id" bigint NOT NULL,
	"rank" smallint NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "club_languages_pkey" PRIMARY KEY("club_id","language_id"),
	CONSTRAINT "club_languages_club_id_rank_key" UNIQUE("club_id","rank"),
	CONSTRAINT "club_languages_rank_check" CHECK ((rank > 0) AND (rank <= 20))
);
--> statement-breakpoint
CREATE TABLE "app"."club_avatars" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.club_avatar_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"club_id" bigint NOT NULL,
	"avatar1" text,
	"avatar2" text,
	"avatar3" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "club_avatars_club_id_key" UNIQUE("club_id")
);
--> statement-breakpoint
ALTER TABLE "app"."club_admins" ADD CONSTRAINT "club_admins_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_admins" ADD CONSTRAINT "club_admins_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "app"."users"("uuid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_activities" ADD CONSTRAINT "club_activities_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_activities" ADD CONSTRAINT "club_activities_activity_id_fkey" FOREIGN KEY ("activity_id") REFERENCES "app"."activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_languages" ADD CONSTRAINT "club_languages_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_languages" ADD CONSTRAINT "club_languages_language_id_fkey" FOREIGN KEY ("language_id") REFERENCES "app"."languages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."club_avatars" ADD CONSTRAINT "club_avatars_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;
