CREATE TABLE "app"."seasons" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."app.seasons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"club_id" bigint NOT NULL,
	"name" varchar(30) NOT NULL,
	"short_name" varchar(8) NOT NULL,
	"season_start" date NOT NULL,
	"season_end" date NOT NULL,
	"for_teams" boolean NOT NULL,
	"for_locations" boolean NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "seasons_club_id_short_name_key" UNIQUE("club_id","short_name"),
	CONSTRAINT "seasons_end_gte_start_check" CHECK (season_end >= season_start)
);
--> statement-breakpoint
ALTER TABLE "app"."seasons" ADD CONSTRAINT "seasons_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "app"."clubs"("id") ON DELETE cascade ON UPDATE no action;
