CREATE TABLE "app"."roles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"role" varchar(30) NOT NULL,
	"role_short" varchar(10) NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "roles_role_key" UNIQUE("role"),
	CONSTRAINT "roles_role_short_key" UNIQUE("role_short")
);
