CREATE TABLE "app"."colors" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."colors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"color" varchar(30) NOT NULL,
	"hex" varchar(7) NOT NULL,
	"is_public" boolean DEFAULT true NOT NULL,
	"is_text_black" boolean DEFAULT true NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "colors_color_key" UNIQUE("color")
);
