CREATE TABLE "app"."statuses" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."statuses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"status" varchar(30) NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "statuses_status_key" UNIQUE("status")
);
