export {
  AVATAR1_SIZE_PX,
  AVATAR2_SIZE_PX,
  AVATAR3_SIZE_PX,
  AVATAR_MEDIUM_MAX_PX,
  AVATAR_SMALL_MAX_PX,
  MAX_AVATAR_BYTES,
  avatarObjectKey,
  buildAvatarVariants,
  clubAvatarObjectKey,
  decodeAvatarInput,
  detectAvatarFormat,
  type AllowedAvatarFormat,
  type AvatarVariants,
} from "@/shared/images/avatar-image";
